server:
    port: 9999
    servlet:
        context-path: /demo
spring:
    application:
        name: seata-springboot-app
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/seata_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456

mybatis-plus:
    mapper-locations: classpath*:com/example/seata/mapper/xml/*Mapper.xml
    global-config:
        # 关闭MP3.0自带的banner
        banner: false
        db-config:
            #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
            id-type: 0
            # 默认数据库表下划线命名
            table-underline: true

logging:
    level:
        io.seata: info
        io.seata.samples.springboot.sys.domain: debug